### ISSUE TITLE
allow for dynamic HUD placement

### ISSUE THREAD

**Issue by Clyme** [legoraft/simple-armor-hud#11]
I am aware at least one previous issue goes in a similar direction, but I want to suggest generalizing this, for arbitrary compatibility between this mod and any modifications done to the hotbar. In this specific case, [Double Hotbar](https://www.curseforge.com/minecraft/mc-mods/double-hotbar/) pushes the armor hud into the xp bar. Having two config sliders for X and Y position respectively would be  decent solution.

![image](https://user-images.githubusercontent.com/40283399/160937030-a738de9a-4458-4d37-8aa8-321428a031f2.png)

**Comment by LegoRaft** [comment]
I will consider adding these config sliders, but as I don't have a lot of time at the moment, I'll prioritize other bug reports and add this feature as soon as I have the time to do this

**Comment by JuceDoesThings** [comment]
Would love for this to be asdded, right now it looks way too gross for me to really use

**Comment by LegoRaft** [comment]
I will take a look at this for the coming mod update, however I'm quite busy at the moment so there will be some delay. If you have some suggestions for this feature, please leave them here

**Comment by legoraft** [comment]
Code for configuration screen: [skin layers 3d](https://github.com/tr7zw/3d-Skin-Layers/blob/1.19/Shared/src/main/java/dev/tr7zw/skinlayers/SkinLayersModBase.java)

**Comment by legoraft** [comment]
Currently, there is a release with a configuration file in which you can enable `better_mount_hud` or `double_hotbar` options. There will be more options and a configuration screen in the near future

**Comment by legoraft** [comment]
This has been fixed as of the latest merge #37, it has mod detection and the config options have been there for a long time
