### ISSUE TITLE
Hotbar becomes dark

### ISSUE THREAD

**Issue by Uberlol** [legoraft/simple-armor-hud#12]
Hotbar becomes black when in a match on pvplegacy (play.pvplegacy.net)

not sure how to reproduce this bug, I tried replicating it on a single player world and a server by wearing armor/a kit but couldn't replicate it. The issue is not caused by other mods because I tried it without any other mods and it still happened. It doesn't happen in the lobby but only in a match which might be related to whether wearing armor could be the issue. no resource packs were used.

With mod in a match
![image](https://user-images.githubusercontent.com/66954202/193909767-27ddf794-9257-4a51-b0e8-bb0350c05d05.png)

Without mod in a match
![image](https://user-images.githubusercontent.com/66954202/193909943-b26c21ff-da56-42e5-9316-ab25762dd629.png)

**Comment by legoraft** [comment]
I've seen this happen before, and will try fixing this soon

**Comment by legoraft** [comment]
In which situations do you have this issue? I'm trying to recreate this, currently seems to only apply in singleplayer
