### ISSUE TITLE
Adjust the armor size 

### ISSUE THREAD

**Issue by sladeXD** [legoraft/simple-armor-hud#14]
Hi i am wondering if you will be making a edit to the mod for all version so that we can adjust the sxie of the armor display

**Comment by legoraft** [comment]
I will take a look at this for the gui overhaul I'm planning to do as said in #11

**Comment by legoraft** [comment]
Resizing the armor will most likely not make it into the mod, because the icons are just item stacks. Movable armor will be worked on soon though
