### ISSUE TITLE
Support for Raised hotbar

### ISSUE THREAD

**Issue by TheFruxz** [legoraft/simple-armor-hud#18]
The mod [Raised](https://modrinth.com/mod/raised) introduces a fix to the hotbar, which sadly does not look good with simple-armor-hud installed at the same time (armor too low, not adjusting like the hearts).

It would be great if the armor details also automatically adjusted in height with the hotbar

**Comment by MrMyror** [comment]
bump

**Comment by MrMyror** [comment]
The new Raised update introduces addons, which could be an easier way of implementing this feature...

**Comment by MrMyror** [comment]
This may help
 https://github.com/yurisuika/Raised/wiki/Compatibility#adding-compatibility

I also opened an issue with Raised already and it seems impossible to add compatibility from their end.

**Comment by legoraft** [comment]
Sorry, I can't reproduce this issue

**Comment by RVZO6** [comment]
Oh sorry! This was already solved with Raised 3.0
