### ISSUE TITLE
bubbles cover the armor panel when in magma/soul sand bubbles

### ISSUE THREAD

**Issue by ISteam14** [legoraft/simple-armor-hud#22]
bubbles cover the armor panel when in magma/soul sand bubbles

Steps to reproduce the bug:
1. go into bubbles of magma/soul sand 
2. wait for full air saturation
3. armor overlaps with bubbles

**Screenshots**
![2023-08-12_10 11 20](https://github.com/legoraft/simple-armor-hud/assets/91954858/61e64746-8e21-4631-af4e-f8d471ec4f02)
![2023-08-12_10 11 15](https://github.com/legoraft/simple-armor-hud/assets/91954858/2b70a449-24ff-4a9e-8f77-d057b8a49a3e)

**Comment by legoraft** [comment]
This sounds like a relatively easy bug to fix, just add another criterium to the air if statement, will try to add this asap
