### ISSUE TITLE
Location customization

### ISSUE THREAD

**Issue by Letus252** [legoraft/simple-armor-hud#35]
Hey, I'd like to suggest adding the ability to move the entire armorhud and individual armor pieces to any location a player desires. This enhancement would greatly improve this mod and allow for better customization, especially across different modpacks, which often have varying gui layouts. (+ Grid, like one in the video, would enable users to align all pieces to the same height).

https://github.com/legoraft/simple-armor-hud/assets/117117674/ce18bbac-3ea0-4bd6-aed6-73d011959d68

**Comment by legoraft** [comment]
I don't believe that this feature will fall into the scope of this project and will take a way bigger codebase to implement. I'm closing this as not planned, but maybe will take a look at it at a later time
