### ISSUE TITLE
Alternative display options (replacing the armor bar, and RTL item display)

### ISSUE THREAD

**Issue by TheDinoKingK** [legoraft/simple-armor-hud#36]
**'Replace Armorbar', and "Right to Left Display" options**
I think there should be an option to change the way the armor hud in a way to replace the vanilla armor bar UI with that hud, 
along with an option to switch the item ordering from LTR to RTL to match, 
I think It'd look cleaner if you prefer to remove the armor bar from the hud entirely

**Comment by legoraft** [comment]
I like the replacing of the armor bar and the rtl placement, I'll look into making this in the future

**Comment by TheDinoKingK** [comment]
Awesome!
