### ISSUE TITLE
Fabric: Add support for Elyra Slot/Trinket

### ISSUE THREAD

**Issue by alexweber** [legoraft/simple-armor-hud#39]
**Feature for problem**
There are currently a couple interchangeable mods that allow users to wear an Elyta at the same time as a chest armor, via the [Trinkets](https://modrinth.com/mod/trinkets) API: [Elytra Trinket](https://modrinth.com/mod/elytra_trinket) and [Elytra Slot](https://modrinth.com/mod/elytra-slot).

It would be awesome if, Simple Armor Hud could detect these mods and display an additional item in the HUD for the Elytra when it's in the "cape trinket slot"!

Thanks!

**Comment by viktordimov** [comment]
Upvoting this. Support Trinkets in general if possible.

**Comment by legoraft** [comment]
I will take a look at the trinket mod and implementing this in the armor hud

**Comment by alexweber** [comment]
FYI Simple HUD Enhanced implements this for trinkets in a pretty elegant/simple way: https://github.com/SoRadGaming/Simple-HUD-Enhanced/blob/main/src/main/java/com/soradgaming/simplehudenhanced/utli/TrinketAccessor.java

**Comment by legoraft** [comment]
@alexweber, the code seems nice. Do you have a screenshot of how they do this visually, or perhaps any personal views on how this should look visually?

**Comment by alexweber** [comment]
> @alexweber, the code seems nice. Do you have a screenshot of how they do this visually, or perhaps any personal views on how this should look visually?

Just put it before or after the armor display!

![hud](https://github.com/legoraft/simple-armor-hud/assets/14409/9828876e-1ca7-4928-89e2-6d8554d143fe)

**Comment by Fyoncle** [comment]
legoraft, when is trinket support coming??

**Comment by legoraft** [comment]
I haven't had a lot of time and won't have the coming few months, so I will try to maintain the mod and update to the latest version, but new features are on the backburner due to life things

**Comment by XevenSmith** [comment]
Isisjs
