### ISSUE TITLE
1.20.6 support

### ISSUE THREAD

**Issue by Nilsson321** [legoraft/simple-armor-hud#40]
:>

**Comment by legoraft** [comment]
This is planned, because armor hud relies on spruceui, I need to wait until that is updated first

**Comment by Nilsson321** [comment]
Any update on how it's going?

**Comment by legoraft** [comment]
I'm currently working on creating a configuration screen api, so that I'm no longer relying on other dependencies, this will delay development a little though.

**Comment by legoraft** [comment]
This issue is fixed as of [ea1a2e1](https://github.com/legoraft/simple-armor-hud/commit/ea1a2e1e697a0ff1a5da774f3db194cb91810aa4). You can download a preliminary update from [here](https://github.com/legoraft/simple-armor-hud/actions/runs/9320697546/artifacts/1556711025)
