### ISSUE TITLE
[Horse Health Clipping] in version [1.20.1 Fabric]

### ISSUE THREAD

**Issue by Fyoncle** [legoraft/simple-armor-hud#41]
**Description**
![image](https://github.com/legoraft/simple-armor-hud/assets/63975256/e1526758-37bc-4829-af77-5968d6a9dc73)
It is what it is :v i don't know what mod was adding your hunger bar in the riding too, but it just happens to be getting inside of hearts of the horse.

**Reproduction**
Steps to reproduce the bug:
1. Download Elysium Days Modpack 3.2.0
2. Tame a horse and get on it.
3. See the glitch.

**Comment by Fyoncle** [comment]
[ITS NOT LEAVE MY BARS ALONE.]

**Comment by legoraft** [comment]
are you sure that you don't have a mod like better mount hud in the pack? Because my mod doesn't do this.

If you want the armor hud to not conflict: In the mod menu, config settings there should be a toggle called better mount hud. This will fix this behaviour.

**Comment by legoraft** [comment]
I've researched the modpack, better mount hud is a part of it. You can edit this in the config, so I'll close this as resolved

**Comment by Fyoncle** [comment]
> I've researched the modpack, better mount hud is a part of it. You can edit this in the config, so I'll close this as resolved

Edit what in the config? Both your mod and this mod doesn't have a config to fix this overlapping issue

**Comment by legoraft** [comment]
If the mod is working correctly on your machine you should be able to access the simple armor hud menu from the mod menu interface. You can change the "better mount hud" option to true to fix this issue. If that deosn't work you can go into your minecraft folder, go in the `config` directory and change the `better_mount_hud` option to true in the `armorhud.properties` file. I hope this works. If you still have a question, I'd be happy to answer!

**Comment by Fyoncle** [comment]
> If the mod is working correctly on your machine you should be able to access the simple armor hud menu from the mod menu interface. You can change the "better mount hud" option to true to fix this issue. If that deosn't work you can go into your minecraft folder, go in the `config` directory and change the `better_mount_hud` option to true in the `armorhud.properties` file. I hope this works. If you still have a question, I'd be happy to answer!

I was searching for SIMPLE armor hud... not armorhud, config name is a little weird, and i didnt been able to see a config screen in the mod menu panel. So thats kinda weird, but thanks for the info!

**Comment by legoraft** [comment]
Yeah, the config file isn't really made for the end user... The config screen in mod menu has been added since [1.4.4](https://github.com/legoraft/simple-armor-hud/releases/tag/v1.4.4-1.21), so could it be that you are using an older version?
