### ISSUE TITLE
[QUESTION] Third Party Client Including This Mod

### ISSUE THREAD

**Issue by Fyoncle** [legoraft/simple-armor-hud#45]
![image](https://github.com/legoraft/simple-armor-hud/assets/63975256/ef8a7aa0-22f9-44c2-b11a-ddc79e7dd1cc)
A third party client called "Hoplite" is including your mod built-in, just curious if they have permission or not.

Asking this because there was a drama happened about Feather Client because they also used built-in mods without permission.

**Comment by legoraft** [comment]
They don't have explicit permission to use simple armor hud in their launcher. I also haven't been contacted by any devs.

**Comment by Fyoncle** [comment]
> They don't have explicit permission to use simple armor hud in their launcher. I also haven't been contacted by any devs.

Ah okay, thanks for the answer, was just wondering.

**Comment by legoraft** [comment]
They also don't seem to claim that they built the mods, they just give you an easy installer for their pvp server. Just a shame that the traffic won't go through modrinth.
