### ISSUE TITLE
[BUG] in version [1.4.4]

### ISSUE THREAD

**Issue by Nilsson321** [legoraft/simple-armor-hud#47]
Hello, when i use this mod the item that i hold do not show the name.

**Reproduction**
Steps to reproduce the bug: Having it instlled

**Comment by legoraft** [comment]
Oh, I hadn't checked this during testing. I will go after this as soon as possible

**Comment by Nilsson321** [comment]
Will a version that fix this be publiced soon?

**Comment by legoraft** [comment]
The version will be published soon, probably tomorrow or the day after when I have time

**Comment by legoraft** [comment]
I have just released the version, check it out on [github](https://github.com/legoraft/simple-armor-hud/releases/tag/v1.4.5-1.21) or [modrinth](https://modrinth.com/mod/simple-armor-hud/version/1.4.5-1.21)
