### ISSUE TITLE
Not Showing Armor in version 1.4.5

### ISSUE THREAD

**Issue by honzanugeta** [legoraft/simple-armor-hud#50]
**Description**
A clear description about your bug and the behavior that's expected:

Armor isn't showing on top of the inventory bar, i used to use the one for minecraft 1.20 and it worked perfectly

**Reproduction**
Steps to reproduce the bug:
1.Open Minecraft
2. Load World or connect to Server
3. put on armor 
4. See that armor isnt shown on top of inventory bar

**Screenshots**
Add screenshots/videos if possible

![image](https://github.com/legoraft/simple-armor-hud/assets/100222360/947c6327-989a-49b9-9b10-b8f23bd1209b)
![image](https://github.com/legoraft/simple-armor-hud/assets/100222360/7eb85fa0-303c-4dbf-ae76-2061d7b8d869)
![image](https://github.com/legoraft/simple-armor-hud/assets/100222360/f314d38c-ba82-4f76-b95e-0d651476a515)

**Comment by legoraft** [comment]
Have you checked in the config screen if the hud is active? You can do this through modmenu, clicking on the mod and clicking on the three bars for the config.

**Comment by honzanugeta** [comment]
Huh, checked through ModMenu and all of the settings were off. Would be better if some of the necessary settings were on by default. 
Thanks for the fix!

**Comment by legoraft** [comment]
the armor hud should be on by default, I think that your config was a one-off

**Comment by honzanugeta** [comment]
Weird, eh it happens
