### ISSUE TITLE
Held Item Tooltips do not work with the mod installed in version [1.20.6]

### ISSUE THREAD

**Issue by Lucipo** [legoraft/simple-armor-hud#52]
**Description**
With the mod installed, held items do not show their name above the hotbar

**Reproduction**
Go into a world
Switch hotbar slots
expected behavior is for the item to appear and fade out that you're holding
with the mod it doesnt

latest log: https://pastebin.com/hTzV2etD

**Comment by legoraft** [comment]
This is already a known issue (#47), it's also fixed in the latest version. I am not planning on backporting all the current fixes to previous versions, so the only solution I can offer you is to update the game or accept that the item names aren't visible.
