### ISSUE TITLE
Armor icons interferes with mount HUD

### ISSUE THREAD

**Issue by Mefiresu** [LegoRaft/simple-armor-hud#6]
The armor icons are drawn on top of the horse's HP bar when the horse has more than 10 hearts. This also affects creative mode.

**Screenshots**

Survival mode
![survival](https://user-images.githubusercontent.com/15063879/134718317-843e4274-3ec8-4460-8ad7-b700b7dbc101.png)

Creative mode
![creative](https://user-images.githubusercontent.com/15063879/134718328-810798f2-870a-497b-b1d6-3d5d68040b12.png)

**Comment by LegoRaft** [comment]
Found a way to move armor up when player is riding an entity using `hasVehicle()` but still finding a way to detect if it's a horse with more than 20 health

**Comment by LegoRaft** [comment]
added a check for if player is riding, and if the mounts health is over 20, armor will move up then, in both survival and creative
