### ISSUE TITLE
Resize and Move Displayed Armor Icons

### ISSUE THREAD

**Issue by LOLboy199** [LegoRaft/simple-armor-hud#7]
Would there be any way to add a menu with options that would allow either/both resizing of the displayed icons or moving the location on the screen where they are displayed?

**Comment by LegoRaft** [comment]
Resizing the armor icons is not possible, because they use the standard inventory icon size, which can't be resized. Moving the hud would be possible though, where would you want the hud to move to?

**Comment by LOLboy199** [comment]
Oh I see. Well I'm not too sure then in that case. I was basically just thinking of sizing them down and moving it straight down. 

What about being able to adjust opacity of the icons? Would that be possible?

**Comment by LegoRaft** [comment]
I can take a look at opactiy, and I also could take a look about sizing them down, but they're probably just bound to the gui scale

**Comment by LegoRaft** [comment]
don't think I'll ever add this
