### ISSUE TITLE
Ridable mount health overwites the Armor HUD in version 1.18.1

### ISSUE THREAD

**Issue by Scarlaid** [legoraft/simple-armor-hud#9]
**Description**
Like the title said
I used both [BetterMountHUD](https://www.curseforge.com/minecraft/mc-mods/better-mount-hud) and this ArmorHUD mod 

**Reproduction**
Steps to reproduce the bug:

1. Install both the mod

2. Ride a horse

3. You will get the under issue

**Screenshots**
![image](https://user-images.githubusercontent.com/90851437/153799259-7ac426a6-e896-4796-8fb7-ab7ccd919e0c.png)

**Comment by LegoRaft** [comment]
just contacted the owner of bettermounthud, will work on a fix as fast as possible!

**Comment by Lortseam** [comment]
I had some more thoughts about this and here is what you could do to fix this issue:

### 1. Dynamically adjust the height (y) of your armor hud depending on which bars are visible
On the right side above the hotbar, there can be the player's food, the mount health and the oxygen. All of these bars can be visible or hidden, depending on what the player is currently doing and in which state he is. For example, the oxygen is only visible when the player is underwater. Additionally, the mount health can consist of two bars if the mount has more than 20 health (this can be seen in the screenshot above).  
When Better Mount HUD is installed, the food and mount health can both be visible at the same time, which is not possible in vanilla Minecraft.
Now, to actually implement this, you would have to get the height (y) of the upmost bar, and place your armor hud above that bar.

### 2. Move your armor hud to another place
I don't know if this is an option, but moving your armor hud to another place would be a workaround for issues like this.

**Comment by Lortseam** [comment]
My reply was actually addressed to the creator of this mod, sorry if that wasn't clear.

**Comment by Scarlaid** [comment]
oh okay, sorry bout that

**Comment by LegoRaft** [comment]
@Lortseam, thanks for all the help! will try to fix this as soon as possible.

**Comment by Lortseam** [comment]
I don't really know what's the best way to do this, you proabably need to create a mixin method for each of the bars and check that by yourself.

**Comment by LegoRaft** [comment]
As I don't have a lot of time to do a lot of research pn this problem and don't have the experience to fix this quickly, this fix will take some time, but I'll put all the free time I have into this bug report

**Comment by legoraft** [comment]
This issue has been resolved in commit [a1e6b02](https://github.com/legoraft/simple-armor-hud/commit/a1e6b02f08288d91a7a0ee2d88f97d77b7a9f936), by adding a config file option for better mount hud
